var usr_markers =
[{
	"name": "Poklad",
	"desc": "Poklad I",
	"desc2": "Vstupte do domu a zahněte doleva, poté použijte žebřík.",
	"req": "lockpicking",
	"level": "hard",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [651,1920],
	"verified": "yes"
},
{
	"name": "Poklad",
	"desc": "Poklad II",
	"desc2": "Hrob, vykopej rýčem.",
	"req": "spade",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
  "coords": [382,1815],
	"verified": "yes"
},
{
	"name": "Poklad",
	"desc": "Poklad III",
	"desc2": "Za starým domem.",
	"req": "lockpicking",
	"level": "very_hard",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [224,1697],
	"verified": "yes"
},
{
	"name": "Poklad",
	"desc": "Poklad IV",
	"desc2": "Ve vchodu do jeskyně.",
	"req": "lockpicking",
	"level": "very_hard",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [2777,1449],
	"verified": "yes"
},
{
  "name": "Poklad",
	"desc": "Poklad V",
	"desc2": "Pytel uvnitř vyschlé studny.",
	"req": "Nic",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [2086,2054],
	"verified": "yes"
},
{
	"name": "Poklad",
	"desc": "Poklad VI",
	"desc2": "",
	"req": "lockpicking",
	"level": "hard",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [2269,1587],
	"verified": "yes"
},
{
	"name": "Poklad",
	"desc": "Poklad VII",
	"desc2": "V lesní zahradě.",
	"req": "lockpicking",
	"level": "hard",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [1861,1520],
},
{
	"name": "Poklad",
	"desc": "Poklad VIII",
	"desc2": "Pytel za holým stromem.",
	"req": "Nic",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [2333,1122],
},
{
	"name": "Poklad",
	"desc": "Poklad IX",
	"desc2": "Hned vedle kamenného mostu.",
	"req": "Nic",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [869,3279],
},
{
	"name": "Poklad",
	"desc": "Poklad X",
	"req": "spade",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [1685,938],
},
{
	"name": "Poklad",
	"desc": "Starověký poklad V",
	"desc2": "Vedle rozbité chatrče poblíž loviště Vysoké.",
	"req": "lockpicking",
	"level": "very_hard",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [476,3868],
	"verified": "yes"
},
/* Needs verification */
{
    "name": "Poklad",
    "desc": "Poklad XI",
		"req": "Nic",
		"level": "",
    "group": "treasure_chest",
    "icon": "treasure_chest",
    "coords": [1444,1141],
},
{
	"name": "Poklad",
	"desc": "Poklad XII",
	"req": "lockpicking",
	"level": "hard",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [3179,333],
},
{
	"name": "Poklad",
	"desc": "Poklad XIII",
	"req": "lockpicking",
	"level": "easy",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [3613,719],
},
{
    "name": "Poklad",
    "desc": "Poklad XIV",
		"req": "spade",
		"level": "",
    "group": "treasure_chest",
    "icon": "treasure_chest",
    "coords": [3687,1259],
},
{
    "name": "Poklad",
    "desc": "Poklad XV",
		"req": "spade",
		"level": "",
    "group": "treasure_chest",
    "icon": "treasure_chest",
    "coords": [2943,1331],
},


{
	"name": "Poklad",
	"desc": "Poklad XVI",
	"req": "spade",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [481,2575],
},
{
	"name": "Poklad",
	"desc": "Poklad XVII",
	"req": "spade",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [770,2566],
},
{
	"name": "Poklad",
	"desc": "Poklad XVIII",
	"req": "lockpicking",
	"level": "easy",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [2496,2821],
},
{
	"name": "Poklad",
	"desc": "Poklad XIX",
	"desc2": "Hrob na malém ostrůvku u řeky.",
	"req": "spade",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [862,1339],
},
{
    "name": "Poklad",
    "desc": "Poklad XX",
    "desc2": "Pod stromem.",
    "req": "lockpicking",
    "level": "easy",
    "group": "treasure_chest",
    "icon": "treasure_chest",
		"coords": [741, 3700],
},
{
    "name": "Poklad",
    "desc": "Poklad XXI",
		"desc2": "Vstupte do dolu severovýchodně od této truhly, slezte po 3 žebřících dolů, pak se držte levé stěny a slezte po 3 žebřících dolů.",
    "req": "lockpicking",
    "level": "very_hard",
    "group": "treasure_chest",
    "icon": "treasure_chest",
    "coords": [659,3143],
},
{
	"name": "Poklad",
	"desc": "Poklad XXII",
	"desc2": "Pytel vedle zničené šibenice.",
	"req": "Nic",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [601,613],
},
{
    "name": "Poklad",
    "desc": "Poklad XXIII",
    "desc2": "V malé jeskyni",
    "group": "treasure_chest",
    "icon": "treasure_chest",
    "coords": [1011,3971],
},
{
    "name": "Poklad",
    "desc": "Poklad XXIV",
    "group": "treasure_chest",
    "icon": "treasure_chest",
    "req": "spade",
    "coords": [901,3842],
},
{
    "name": "Poklad",
    "desc": "Poklad XXV",
    "req": "spade",
  	"level": "",
    "group": "treasure_chest",
    "icon": "treasure_chest",

		"skillbooklvl": "15",
    "coords": [218,3475],
},

/*

	// --ANCIENT TREASURE--

*/
{
	"name": "Poklad",
	"desc": "Starověký poklad I",
	"req": "spade",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [3872,880],
},
{
	"name": "Poklad",
	"desc": "Starověký poklad II",
	"desc2": "Hledejte velký kámen vedle jeskyně.",
	"req": "Nic",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [871,270],
},
{
	"name": "Poklad",
	"desc": "Starověký poklad III",
	"req": "spade",
	"level": "",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [3155,3838],
},
{
	"name": "Poklad",
	"desc": "Starověký poklad IV",
	"req": "lockpicking",
	"level": "easy",
	"group": "treasure_chest",
	"icon": "treasure_chest",
	"coords": [1720,780],
},
/*

	// --TREASURE MAPS--

*/
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu I",
	"desc2": "V mlýně na sudu po výstupu po žebříku.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [1397,1446],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu II",
	"desc2": "Jakmile vstoupíte jižní branou kláštera, vyjděte po schodech doleva a pokračujte, dokud se nedostanete do honosné ložnice v omezeném prostoru, mapa je na stole vedle postele.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [940,1640],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu III",
	"desc2": "Lze koupit od Mistra Freskaře (budete si s ním moci mluvit až později ve hře).",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [890,1432],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu IV",
	"desc2": "Jde koupit od bratra Nikodéma.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [902,1683],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu V",
	"desc2": "Jde koupit od mlynáře Vojtěcha",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2821,1234],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu VI",
	"desc2": "Jde koupit od jednoho z Poutníků, se kterými se můžete setkat pouze při rychlém cestování.",
	"group": "treasure_map",
	"icon": "treasure_map_alt",
	"coords": [1630,2246],                                           // -! WAYFARER MAP !-
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu VII",
	"desc2": "V klášterní knihovně, u severní zdi na hromadě knih.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [967,1641],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu VIII",
	"desc2": "Vstupte do větrného mlýna a vyjděte po schodech nahoru, najdete ji na dřevěném trámu.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2743,3695],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu IX",
	"desc2": "Na stole v malé chatrči.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [421,3559],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu X",
	"desc2": "V zamčené truhle v nejseverovýchodnější kamenné budově.",
	"req": "lockpicking",
	"level": "easy",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2864,1937],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XI",
	"desc2": "Jde koupit od kupce Votavy.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2334,2821],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XII",
	"desc2": "Jde koupyt od mlynaře Peška.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2459.114258,704.810425],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XIII",
	"desc2": "Jde koupit od bylináře.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [3247,1522],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XIV",
	"desc2": "Jde koupit od jednoho z Poutníků, se kterými se můžete setkat pouze při rychlém cestování.",
	"group": "treasure_map",
	"icon": "treasure_map_alt",
	"coords": [2016,2178],                                           // -! WAYFARER MAP !-
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XV",
	"desc2": "Jděte po schodech, vstupte prvními dveřmi do prvního patra, na konci chodby zahněte dveřmi doleva a podívejte se na mapu nahoře na skříni.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2575,445],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XVI",
	"desc2": "Jde koupit od bylináře.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [945,2340],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XVII",
	"desc2": "Jde koupit od lovce Bertholda",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2629,646],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XVIII",
	"desc2": "Jde koupit od lovce Nikolase.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2444.702881,2643.914063],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XIX",
	"desc2": "Jde koupit od jednoho z Poutníků, se kterými se můžete setkat pouze při rychlém cestování.",
	"group": "treasure_map",
	"icon": "treasure_map_alt",
	"coords": [2286,2174],                                           // -! WAYFARER MAP !-
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XX",
	"desc2": "Jde koupit od bylináře Šarlatána.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [906,1204],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XXI",
	"desc2": "V otevřené stodole na sudu (k jeho sebrání budete možná muset skočit na kbelík vedle něj)",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [396,3090],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XXII",
	"desc2": "Jděte po schodech hned vedle krejčího, projděte prvními dvěma dveřmi a zahněte doprava, abyste vyšli po dalších schodech nahoru a jděte dalšími dveřmi doleva. Mapa je na levé straně na spodní polici knihovny.",
	"req": "lockpicking",
	"level": "very_hard",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2517,551],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XXIII",
	"desc2": "Vylezte po žebříku, který je opřený o statek, mapa je na sudu po pravé straně.",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [3530,2607],
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XXIV",
	"desc2": "Jde koupit od jednoho z Poutníků, se kterými se můžete setkat pouze při rychlém cestování.",
	"group": "treasure_map",
	"icon": "treasure_map_alt",
	"coords": [2642,2010],                                           // -! WAYFARER MAP !-
},
{
	"name": "<span data-i18n='treasure_map'>Mapa k pokladu</span>",
	"desc": "Mapa k pokladu XXV",
	"desc2": "Vstupte do hostince a odbočte doleva, sejděte po druhém malém schodišti, abyste otevřeli dveře do sklepa. Jakmile vejdete, mapa je na sudu po pravé straně.",
	"req": "lockpicking",
	"level": "easy",
	"group": "treasure_map",
	"icon": "treasure_map",
	"coords": [2907,745],
}]
